apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtomcat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springtomcat
  template:
    metadata:
      labels:
        app: springtomcat
    spec:
      containers:
      - name: springtomcat
        image: snowpeak.azurecr.cn/springtomcat:0.2
        ports:
        - containerPort: 80